sudo: false
language: ruby
cache: bundler
before_install: gem install bundler -v '< 2.0'
install: bundle install --with test --without development production
services:
  - redis-server
before_script:
  - bundle exec rake redis:populate
  - bundle exec thin start -R config.ru -e $RACK_ENV &
script: bundle exec rspec
rvm:
  - 2.3.1
branches:
  only: master
notifications:
  email: false
