sudo: false
language: ruby
cache: bundler
before_install: gem install bundler -v 1.16.3
install: bundle _1.16.3_ install --with test --without development production
services:
  - redis-server
before_script:
  - bundle _1.16.3_ exec rake redis:populate
  - bundle _1.16.3_ exec thin start -R config.ru -e $RACK_ENV &
script: bundle _1.16.3_ exec rspec
rvm:
  - 2.3.1
branches:
  only: master
notifications:
  email: false
